### ISSUE TITLE
EnvironmentLogger attribute parsing

### ISSUE THREAD

**Issue by max-zilla** [terraref/extractors-environmental#16]
@FlyingWithJerome @czender the EnvironmentLogger isn't pushing to geostreams properly. The python code:
```
stream_list = set([getattr(data, u'sensor') for data in netCDF_handle.variables.values() if u'sensor' in dir(data)])
        for stream in stream_list:
            # STREAM is plot x instrument
            stream_name = "EnvLog %s - Full Field" % stream
            <get or create stream_id>

            try:
                memberlist = netCDF_handle.get_variables_by_attributes(sensor=stream)
                for members in memberlist:
                    data_points = _produce_attr_dict(members)

                    for index in range(len(data_points)):
                        <create datapoint>
            except:
                logging.error("NetCDF attribute not found: %s" % stream)
```

When I run this on a test EL file (https://terraref.ncsa.illinois.edu/clowder/files/5900b29c4f0ce950158b8a30) I get errors:
```
2017-04-26 15:55:32,725 [Thread-2       ] DEBUG   : pyclowder.geostreams - found sensor 'Full Field - Environmental Logger' = [358]
2017-04-26 15:55:32,767 [Thread-2       ] DEBUG   : pyclowder.geostreams - found stream 'EnvLog sensor_weather_station - Full Field' = [746]
2017-04-26 15:55:32,768 [Thread-2       ] ERROR   : root - NetCDF attribute not found: sensor_weather_station
2017-04-26 15:55:32,802 [Thread-2       ] DEBUG   : pyclowder.geostreams - found stream 'EnvLog sensor_par - Full Field' = [747]
2017-04-26 15:55:32,802 [Thread-2       ] ERROR   : root - NetCDF attribute not found: sensor_par
2017-04-26 15:55:32,836 [Thread-2       ] DEBUG   : pyclowder.geostreams - found stream 'EnvLog sensor_spectrum - Full Field' = [748]
2017-04-26 15:55:32,837 [Thread-2       ] ERROR   : root - NetCDF attribute not found: sensor_spectrum
2017-04-26 15:55:32,870 [Thread-2       ] DEBUG   : pyclowder.geostreams - found stream 'EnvLog sensor_co2 - Full Field' = [749]
2017-04-26 15:55:32,871 [Thread-2       ] ERROR   : root - NetCDF attribute not found: sensor_co2
2017-04-26 15:55:32,873 [Thread-2       ] INFO    : pyclowder.connectors - [5900b29c4f0ce950158b8a30] : DONE: Done processing
```

There's something broken in get_variables_by_attributes usage here. 

Before I wrote the try/catch here is the raw error I was seeing:
```
2017-04-26 15:52:00,764 [Thread-1       ] ERROR   : pyclowder.connectors - [5900c0b24f0ce950158bdbba] standard error : NetCDF: Attribute not found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyclowder/connectors.py", line 219, in _process_message
    self.process_message(self, host, secret_key, resource, body)
  File "/home/extractor/extractors-environmental/environmentlogger/terra_environmentlogger.py", line 98, in process_message
    prepareDatapoint(connector, host, secret_key, resource, out_netcdf)
  File "/home/extractor/extractors-environmental/environmentlogger/terra_environmentlogger.py", line 141, in prepareDatapoint
    for members in netCDF_handle.get_variables_by_attributes(sensor=stream):
  File "netCDF4.pyx", line 1853, in netCDF4.Dataset.__getattr__ (netCDF4.c:23947)
  File "netCDF4.pyx", line 1798, in netCDF4.Dataset.getncattr (netCDF4.c:23210)
  File "netCDF4.pyx", line 922, in netCDF4._get_att (netCDF4.c:14731)
AttributeError: NetCDF: Attribute not found
```

I'm guessing this is probably a simple fix but I am not familiar with netCDF4 library and thought you might know quickly.

**Comment by max-zilla** [comment]
here's link to code in current base: https://github.com/terraref/extractors-environmental/blob/master/environmentlogger/terra_environmentlogger.py#L116

**Comment by rachelshekar** [comment]
Finding attributes from netcdf headers @FlyingWithJerome - please check errors above

**Comment by FlyingWithJerome** [comment]
@max-zilla @rachelshekar 
I will follow up on this issue.

**Comment by max-zilla** [comment]
@FlyingWithJerome hopefully I didn't break something when i moved geostreams code into extractor. tried to replicate what you had.

**Comment by max-zilla** [comment]
@FlyingWithJerome sorry, also make sure you pull latest code before looking. renamed main environmentlogger directory and script recently:
https://github.com/terraref/extractors-environmental/tree/master/envlog2netcdf

**Comment by max-zilla** [comment]
@FlyingWithJerome any updates on this one?

**Comment by FlyingWithJerome** [comment]
@max-zilla 
Sorry, just finished midterms yesterday - will get into this tomorrow.

**Comment by FlyingWithJerome** [comment]
@max-zilla 
Hi Max, sorry for the delay. I see where the problem is, but the problem is that I have no place to reproduce it, since my local machine doesn't have "dateutil" module (nor it is available on pip), and ROGER doesn't have pyclowder.

Can I know where to install the "dateutil" module?

**Comment by max-zilla** [comment]
@FlyingWithJerome I think this is what you want:
https://pypi.python.org/pypi/python-dateutil
```
pip install python-dateutil
```

**Comment by FlyingWithJerome** [comment]
@max-zilla 
Thanks, after running the [script](https://github.com/terraref/extractors-environmental/blob/master/environmentlogger/terra_environmentlogger.py), here is the error message I got:

```bash
Joy-Maniac:envlog2netcdf jeromemao$ python terra_envlog2netcdf.py
2017-05-15 10:43:49,305 [MainThread     ] INFO    : pika.adapters.base_connection - Connecting to 127.0.0.1:5672
2017-05-15 10:43:49,306 [MainThread     ] WARNING : pika.adapters.base_connection - Connection to 127.0.0.1:5672 failed: [Errno 61] Connection refused
2017-05-15 10:43:49,306 [MainThread     ] WARNING : pika.connection - Could not connect, 0 attempts left
Traceback (most recent call last):
  File "terra_envlog2netcdf.py", line 204, in <module>
    extractor.start()
  File "/usr/local/bin/conda/lib/python2.7/site-packages/pyclowder/extractors.py", line 138, in start
    rconn.connect()
  File "/usr/local/bin/conda/lib/python2.7/site-packages/pyclowder/connectors.py", line 449, in connect
    self.connection = pika.BlockingConnection(parameters)
  File "/usr/local/bin/conda/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 339, in __init__
    self._process_io_for_connection_setup()
  File "/usr/local/bin/conda/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 374, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/usr/local/bin/conda/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 395, in _flush_output
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed
```

Is that because I need to connect with some special IP address?

**Comment by max-zilla** [comment]
@FlyingWithJerome you'd need some secret API keys to run the actual extractor against the production RabbitMQ queue if that's what you're trying to do. That is trying to connect to a local RabbitMQ instance at 127.0.0.1:5672 - if you want to run Clowder locally you can run RabbitMQ and upload one of the envlog files locally to trigger it.

However it might be faster/easier to just to some python debugging directly. If you download the .json file (https://terraref.ncsa.illinois.edu/clowder/files/59019b844f0c38c084d297f7?dataset=59005e504f0ce950158a4139&space=) and in python run mainProgramTrigger on it:
https://github.com/terraref/extractors-environmental/blob/master/envlog2netcdf/terra_envlog2netcdf.py#L87

...followed by the problematic header code in prepareDatapoints:
https://github.com/terraref/extractors-environmental/blob/master/envlog2netcdf/terra_envlog2netcdf.py#L185 

You should get the error I saw above:
```
for members in netCDF_handle.get_variables_by_attributes(sensor=stream):
  File "netCDF4.pyx", line 1853, in netCDF4.Dataset.__getattr__ (netCDF4.c:23947)
  File "netCDF4.pyx", line 1798, in netCDF4.Dataset.getncattr (netCDF4.c:23210)
  File "netCDF4.pyx", line 922, in netCDF4._get_att (netCDF4.c:14731)
AttributeError: NetCDF: Attribute not found
```

**Comment by max-zilla** [comment]
@FlyingWithJerome any luck?

**Comment by czender** [comment]
@max-zilla haven't forgotten this, thanks for your patience, we will respond to this by tomorrow...

**Comment by max-zilla** [comment]
@FlyingWithJerome I merged your code and ran the new extractor, it doesnt crash anymore but im not sure it's being generated properly:
```
2017-05-24 16:13:48,086 [Thread-1       ] INFO    : root - converting JSON to: /home/extractor/sites/ua-mac/Level_1/EnvironmentLogger/2017-04-27/EnvironmentLogger_lv1_2017-04-27_uamac.nc
2017-05-24 16:13:50,517 [Thread-1       ] INFO    : root - uploading netCDF file to Clowder
2017-05-24 16:13:50,700 [Thread-1       ] DEBUG   : pyclowder.files - uploaded file id = [5925b13e4f0c7920bc82863f]
2017-05-24 16:13:50,740 [Thread-1       ] DEBUG   : pyclowder.geostreams - found sensor 'Full Field - Environmental Logger' = [358]
2017-05-24 16:13:50,759 [Thread-1       ] DEBUG   : pyclowder.geostreams - found stream 'EnvLog sensor_par - Full Field' = [747]
2017-05-24 16:13:50,783 [Thread-1       ] ERROR   : root - NetCDF attribute not found: sensor_par
2017-05-24 16:13:50,802 [Thread-1       ] DEBUG   : pyclowder.geostreams - found stream 'EnvLog sensor_weather_station - Full Field' = [746]
2017-05-24 16:13:50,824 [Thread-1       ] ERROR   : root - NetCDF attribute not found: sensor_weather_station
2017-05-24 16:13:50,844 [Thread-1       ] DEBUG   : pyclowder.geostreams - found stream 'EnvLog sensor_spectrum - Full Field' = [748]
2017-05-24 16:13:50,866 [Thread-1       ] ERROR   : root - NetCDF attribute not found: sensor_spectrum
2017-05-24 16:13:50,885 [Thread-1       ] DEBUG   : pyclowder.geostreams - found stream 'EnvLog sensor_co2 - Full Field' = [749]
2017-05-24 16:13:50,908 [Thread-1       ] ERROR   : root - NetCDF attribute not found: sensor_co2
2017-05-24 16:13:50,956 [Thread-1       ] INFO    : pyclowder.connectors - [5901a99b4f0c38c084d29ce7] : StatusMessage.done: Done processing
```

Are you unable to recreate using the same date as above (04-27)?

**Comment by czender** [comment]
@FlyingWithJerome @max-zilla regarding that error message there are no longer attributes with those names ("sensor_par" etc). We converted them to variables. The "sensor" attribute in each geophysical variable takes on one of those values. I hope this points one of you to the cause of the error...

**Comment by FlyingWithJerome** [comment]
@max-zilla 
Thanks for your feedback.
It behaves weird because [this line](https://github.com/terraref/extractors-environmental/blob/master/envlog2netcdf/terra_envlog2netcdf.py#L161) explicitly asks the netCDF4 to find (and only find) the attribute "sensor." Can the extractor show the traceback of these AttributeError?

**Comment by max-zilla** [comment]
@FlyingWithJerome I re-ran clean this morning and didn't get additional errors, looks like everything is fixed. 
https://terraref.ncsa.illinois.edu/clowder/geostreams/sensors/358

Streams:
```
EnvLog sensor_weather_station - Full Field 
STREAM ID: 746 

EnvLog sensor_par - Full Field 
STREAM ID: 747 

EnvLog sensor_spectrum - Full Field 
STREAM ID: 748 

EnvLog sensor_co2 - Full Field 
STREAM ID: 749
```
